root = "."
tmp_dir = "bin"

[build]
cmd = "go build -o ./bin/peakstreak-dev ./cmd/api/main.go"
bin = "bin/peakstreak-dev"
include_dir = ["cmd", "internal"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["bin", "frontend", "node_modules", "db-data", "migrations"]
log = "air_build.log"
delay = 1000
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
